bloggie/Models/Domain/BlogPost.cs
namespace bloggie.Models.Domain
{
    public class BlogPost
    {

        public Guid Id { get; set; }
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string Content { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string UrlHandle { get; set; }
        public DateTime PublishedDate { get; set; }
        public string Author { get; set; }
        public bool Visible { get; set; }


        public ICollection<Tag> Tags { get; set; }
    }
}

bloggie/Models/Domain/Tag.cs
namespace bloggie.Models.Domain
{
    public class Tag
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }


        public ICollection<BlogPost> BlogPosts { get; set; }

     
    }
}

bloggie/Models/ErrorViewModel.cs
namespace bloggie.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

bloggie/Models/ViewModels/AddTagRequest.cs
namespace bloggie.Models.ViewModels
{
    public class AddTagRequest
    {
        public string Name { get; set; }
        public string DisplayName { get; set; }

    }
}

bloggie/Models/ViewModels/EditTagRequest.cs
namespace bloggie.Models.ViewModels
{
    public class EditTagRequest
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
    }
}

bloggie/Controllers/AdminTagsController.cs
using bloggie.Data;
using bloggie.Models.Domain;
using bloggie.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace bloggie.Controllers
{
    public class AdminTagsController : Controller
    {
        private readonly BloggieDbContext _bloggieDbContext;
        public AdminTagsController(BloggieDbContext bloggieDbContext)
        {
            _bloggieDbContext = bloggieDbContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public IActionResult Add(AddTagRequest addTagRequest)
        {
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName,
            };

            _bloggieDbContext.Tags.Add(tag);
            _bloggieDbContext.SaveChangesAsync();
            return RedirectToAction("List");
        }

        [HttpGet]
        [ActionName("List")]
        public IActionResult List()
        {
           var tags = _bloggieDbContext.Tags.ToList();
            return View(tags);
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {

            var tag = _bloggieDbContext.Tags.FirstOrDefault(x => x.Id == id);

            if (tag is not null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };

                return View(editTagRequest);
            }
            return View(null);
        }

        [HttpPost]
        public IActionResult Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName,
            };

          
            var existingTag = _bloggieDbContext.Tags.Find(tag.Id);
            if (existingTag is not null)
            {
                existingTag.Name = tag.Name;
                existingTag.DisplayName = tag.DisplayName;

                _bloggieDbContext.SaveChanges();

                return RedirectToAction("List");
            }

            else
            {
                return RedirectToAction("List", new {id = editTagRequest.Id});
            }
        }   
    }
}

bloggie/Controllers/HomeController.cs
using bloggie.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace bloggie.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

bloggie/Views/AdminTags/Add.cshtml
@model bloggie.Models.ViewModels.AddTagRequest
@{
}



<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Add New Tag - Admin Functionality</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" id="name" asp-for="Name"/>
        </div>
        <div class="mb-3">
            <label class="form-label">Display Name</label>
            <input type="text" class="form-control" id="displayName" asp-for="DisplayName"/>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

bloggie/Views/AdminTags/Edit.cshtml
@model bloggie.Models.ViewModels.EditTagRequest
@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Edit a Tag - Admin Functionality</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-labe">Id</label>
            <input type="text" id="id" class="form-control" asp-for="Id" readonly />
        </div>

        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" id="name" class="form-control" asp-for="Name" onkeypress="return event.charCode != 32" />
        </div>

        <div class="mb-3">
            <label class="form-labe">Display Name</label>
            <input type="text" id="displayName" class="form-control" asp-for="DisplayName" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Update</button>
        </div>
    </form>
</div>

bloggie/Views/AdminTags/List.cshtml
@model List<bloggie.Models.Domain.Tag>
@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Show All Tags - Admin Functionality</h1>
    </div>
</div>

<div class="container py-5">
    @if (Model is not null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th></th>


                </tr>
            </thead>
            <tbody>
                @foreach(var tag in Model)
                {
                    <tr>
                        <td>@tag.Id</td>
                        <td>@tag.Name</td>
                        <td>@tag.DisplayName</td>
                        <td><a asp-area="" asp-controller="AdminTags" asp-action="Edit" asp-route-id="@tag.Id">Edit</a></td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No tags found!</p>
    }
</div>

bloggie/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

bloggie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bloggie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/bloggie.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">bloggie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags"asp-action="Add">Add</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="List">Show All Tags</a></li>

                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - bloggie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>